apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-zrwvg-47vcp 
  name: cluster-zrwvg-47vcp-tom-ms 
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-zrwvg-47vcp 
      machine.openshift.io/cluster-api-machineset: cluster-zrwvg-47vcp-tom-ms 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-zrwvg-47vcp
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-zrwvg-47vcp-tom-ms 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/role: "" 
      providerSpec:
        value:
          ami:
            id: ami-08bb6907b96d2a024
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-zrwvg-47vcp-worker-profile 
          instanceType: g5.16xlarge
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-east-2c
            region: us-east-2
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - cluster-zrwvg-47vcp-node
            - filters:
                - name: 'tag:Name'
                  values:
                    - cluster-zrwvg-47vcp-lb
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - cluster-zrwvg-47vcp-subnet-private-us-east-2c
          tags:
            - name: kubernetes.io/cluster/cluster-zrwvg-47vcp 
              value: owned
          userDataSecret:
            name: worker-user-data