apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: your_infrastructure_id 
  name: your_infrastructure_id-tom-ms 
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: your_infrastructure_id 
      machine.openshift.io/cluster-api-machineset: your_infrastructure_id-tom-ms 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: your_infrastructure_id
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: your_infrastructure_id-tom-ms 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/role: "" 
      providerSpec:
        value:
          ami:
            id: your_ami
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: your_infrastructure_id-worker-profile 
          instanceType: your_instanceType
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: your_availabilityZone
            region: your_region
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - your_infrastructure_id-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - your_infrastructure_id-private-your_availabilityZone
          tags:
            - name: kubernetes.io/cluster/your_infrastructure_id 
              value: owned
          userDataSecret:
            name: worker-user-data